# The URL the site will be built for
base_url = "https://danielwaechter.com"

# The title/description of the site
title = "Daniel Waechter"
description = "Senior Software Engineer specializing in game servers"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feeds = false
minify_html = true

theme = "tabi"

[markdown]
highlight_code = true
highlight_theme = "css"
render_emoji = true
smart_punctuation = false

[extra]
default_theme = "dark"
skin = "dw_custom"

remote_repository_url = "https://github.com/academician/danielwaechter.com"
remote_repository_git_platform = "auto"
remote_repository_branch = "main"
show_remote_changes = true
show_remote_source = true

# Add a "copy" button to codeblocks (loads ~700 bytes of JavaScript).
copy_button = true

show_reading_time = true

menu = [
  { name = "blog", url = "blog", trailing_slash = true },
  { name = "about", url = "about", trailing_slash = true },
  { name = "resume", url = "/daniel-waechter-resume-2025.pdf", trailing_slash = false },
]

feed_icon = false
full_content_in_feed = true

email = "ZGFuaWVsQGRhbmllbHdhZWNodGVyLmNvbQ=="

socials = [
  { name = "linkedin", url = "https://www.linkedin.com/in/danielwaechter/", icon = "linkedin" },
  { name = "mastodon", url = "https://mastodon.gamedev.place/@danielwaechter", icon = "mastodon" },
  { name = "github", url = "https://github.com/academician", icon = "github" },
]

author = "Daniel Waechter"

[extra.giscus]
enabled_for_all_posts = true
automatic_loading = true
repo = "academician/danielwaechter.com"
repo_id = "MDEwOlJlcG9zaXRvcnkzMzk1MTU5Mzc="
category = "Announcements"
category_id = "DIC_kwDOFDyaIc4CaHhf"
mapping = "slug"
strict_title_matching = 1                    # 1 to enable, 0 to disable.
enable_reactions = 1                         # 1 to enable, 0 to disable.
comment_box_above_comments = true
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = ""                                    # Leave blank to match the page's language.
lazy_loading = true
