# The URL the site will be built for
base_url = "https://danielwaechter.com"

# The title/description of the site
title = "Daniel Waechter"
description = "Senior Software Engineer specializing in game servers"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feed = true
minify_html = true

theme = "hyde"

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
smart_punctuation = false

[extra]
hyde_theme = "theme-base-0d"

hyde_links = [
    { url = "/global/about", name = "About Me" },
    { url = "https://www.linkedin.com/in/danielwaechter/", name = "LinkedIn" },
    { url = "https://mastodon.gamedev.place/@danielwaechter", name = "Mastodon" },
    { url = "https://twitter.com/danielwaechter", name = "Twitter" },
    { url = "https://github.com/academician", name = "Github" },
    { url = "/resume-2023.pdf", name = "Resume" },
]

author = "Daniel Waechter"
